# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N1BpC3NtjORE8ykqWx1Exm1tKE-porT-
"""

import pandas as pd
import matplotlib.pyplot as plt

# Creating a 4*5 array 

a={'Name':['Ankit','Abhay','Arpit','Akash'] , 'Marks':[93,89,79,87] , 'Age':[18,19,18,20] , 'Contact':[9902345654,9917900123,9874599820,8723886006] ,'Study_hour':[8,6,9,10]}
x=pd.DataFrame(a)

x

plt.pie(x['Marks'],labels=x['Name'],explode=[0.1,0.1,0.1,0.1],autopct='%1.1f%%')
plt.show()

a=plt.pie(x['Study_hour'],labels=x['Name'],explode=[0.1,0.1,0.1,0.1],autopct='%1.1f%%')
plt.show()

a=plt.pie(x['Study_hour'],labels=x['Marks'],explode=[0.1,0.1,0.1,0.1],autopct='%1.1f%%')
plt.show()